[tool.poetry]
name = "recipe"
version = "0.1.0"
description = "A way to write down your cooking/baking recipes in Python. This is an actual library, no joke (period). Made with ❤ for everyone with minimum coding literacy."
authors = ["Nutchanon Ninyawee <nutchanon@codustry.com>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
